.Dd February 15, 2023
.Dt INLINECALL 1
.Os
.Sh NAME
.Nm inlinecall
.Nd print call sites of an inline function
.Sh SYNOPSIS
.Nm
.Ar function
.Ar file 
.Sh DESCRIPTION
.Pp
.Nm
finds the call sites of
.Ar function
(if it's an inline function) in
.Ar file
and outputs the results in the following format:
.Bd -literal -offset indent
cu1_func_declaration_file:line
	[low_bound - high_bound]	inline_copy1_file:line	caller_func()
	[low_bound - high_bound]	inline_copy2_file:line	caller_func()
	...
cu2_func_declaration_file:line
	...
.Ed
.Sh SEE ALSO
.Xr dwarf 3 ,
.Xr elf 3 ,
.Xr gelf 3
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@FreeBSD.org
